@echo off

REM Node 250, local console

SET WCNODEID=250
SET WCPORTID=0
SET TWNODE=250
SET NFNODE=250


PATH=c:\windows\system32;C:\PKWARE;C:\ARJ;C:\LHA;C:\WINDOWS\SYSTEM32                 

:RELOAD
C:
CD \WILDCAT
WILDCAT CID:512-555-1212
IF ERRORLEVEL 4 GOTO CHAT
IF ERRORLEVEL 3 GOTO MAIL
IF ERRORLEVEL 2 GOTO DOOR
IF ERRORLEVEL 1 GOTO RELOAD
GOTO END
:MAIL
CD \WILDCAT\WCWORK\NODE%WCNODEID%
\WILDCAT\WCMAIL
GOTO RELOAD
:CHAT
CD \WILDCAT\WCWORK\NODE%WCNODEID%
\WILDCAT\WCCHAT
GOTO RELOAD
:DOOR
IF EXIST C:\WILDCAT\WCWORK\NODE%WCNODEID%\EVENT.BAT GOTO EVENT
CD \WILDCAT\WCWORK\NODE%WCNODEID%
rem Note the "CALL" statement is used here no "CAT.BAT" is needed at the
rem end of your door batch files
CALL DOOR.BAT
GOTO RELOAD
:EVENT
CD \WILDCAT\WCWORK\NODE%WCNODEID%
rem Note the "CALL" statement is used here no "CAT.BAT" is needed at the
rem end of your event batch files
CALL EVENT.BAT
GOTO RELOAD
:END
@echo on
