@echo off

PATH=C:\ARJ;C:\LHA;c:\windows\system32

REM COM 5 - Lower built-in port  irq ?? baseid ??

SET WCNODEID=4
SET TWNODE=4
SET NFNODE=4
SET NFPORT=5
rem SET WCPORTID=4
rem SET WCIRQID=3
rem SET WCBASEID=$2E8
rem SET WCMDM=CARD288F
rem SET WCMDM=USRDSF
SET WCMDM=X25RING

c:\netfoss\netfoss /N%WCNODEID% /C%NFPORT% /L38400

:RELOAD
C:
CD \WILDCAT
REM WILDCAT /B 115200MNP
WILDCAT
IF ERRORLEVEL 4 GOTO CHAT
IF ERRORLEVEL 3 GOTO MAIL
IF ERRORLEVEL 2 GOTO DOOR
IF ERRORLEVEL 1 GOTO RELOAD
GOTO END
:MAIL
CD \WILDCAT\WCWORK\NODE%WCNODEID%
\WILDCAT\WCMAIL
GOTO RELOAD
:CHAT
CD \WILDCAT\WCWORK\NODE%WCNODEID%
\WILDCAT\WCCHAT
GOTO RELOAD
:DOOR
IF EXIST C:\WILDCAT\WCWORK\NODE%WCNODEID%\EVENT.BAT GOTO EVENT
CD \WILDCAT\WCWORK\NODE%WCNODEID%
rem Note the "CALL" statement is used here no "CAT.BAT" is needed at the
rem end of your door batch files
CALL DOOR.BAT
GOTO RELOAD
:EVENT
CD \WILDCAT\WCWORK\NODE%WCNODEID%
rem Note the "CALL" statement is used here no "CAT.BAT" is needed at the
rem end of your event batch files
CALL EVENT.BAT
GOTO RELOAD
:END

c:\netfoss\netfoss /u
@echo on
